
























#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.Specialized;     
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace SiteCoreTrainings.TDS_Entities.TDS_Gen
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }
	}
}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base
{


 	/// <summary>
	/// IBase Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Base/Base</para>	
	/// <para>ID: 07d05738-2e91-4fc4-ba96-ca68e56fed39</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBaseConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBase : IGlassBase 
	{
			
	}


	public static partial class IBaseConstants{

			public const string TemplateIdString = "07d05738-2e91-4fc4-ba96-ca68e56fed39";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base";

			

	}

	
	/// <summary>
	/// Base
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Base/Base</para>	
	/// <para>ID: 07d05738-2e91-4fc4-ba96-ca68e56fed39</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBaseConstants.TemplateIdString)] //, Cachable = true
	public partial class Base  : GlassBase, IBase 
	{
	   
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Pages
{


 	/// <summary>
	/// IArticle_Details Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Article Details</para>	
	/// <para>ID: 11a7b1bf-f409-4a99-9706-6b24224eae33</para>	
	/// </summary>
	[SitecoreType(TemplateId=IArticle_DetailsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IArticle_Details : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Article Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: fe1e0961-6a48-44f0-be52-9af346a068ad</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticle_DetailsConstants.Article_ImageFieldName)]
					Image Article_Image  {get; set;}
			
			
					/// <summary>
					/// The Author field.
					/// <para></para>
					/// <para>Field Type: lookup</para>		
					/// <para>Field ID: f8bcf1db-83ad-47dd-a743-7f5c618d528e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticle_DetailsConstants.AuthorFieldName)]
					Guid Author  {get; set;}
			
			
					/// <summary>
					/// The Date field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 221bce6a-7d28-4a27-b89f-0b450b8ff08e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticle_DetailsConstants.DateFieldName)]
					DateTime Date  {get; set;}
			
			
					/// <summary>
					/// The Likes field.
					/// <para></para>
					/// <para>Field Type: Number</para>		
					/// <para>Field ID: f50e22b6-1e20-4c2d-8863-aefdba844fd2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticle_DetailsConstants.LikesFieldName)]
					float Likes  {get; set;}
			
			
					/// <summary>
					/// The Main Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 60ade6be-767c-48ad-a49f-b55b463ada13</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticle_DetailsConstants.Main_BodyFieldName)]
					string Main_Body  {get; set;}
			
			
					/// <summary>
					/// The Page Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: cbabc9e0-9797-4161-ada9-4b28e871d4a8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticle_DetailsConstants.Page_TitleFieldName)]
					string Page_Title  {get; set;}
			
			
	}


	public static partial class IArticle_DetailsConstants{

			public const string TemplateIdString = "11a7b1bf-f409-4a99-9706-6b24224eae33";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Article Details";

		
			
			public static readonly ID Article_ImageFieldId = new ID("fe1e0961-6a48-44f0-be52-9af346a068ad");
			public const string Article_ImageFieldName = "Article Image";
			
		
			
			public static readonly ID AuthorFieldId = new ID("f8bcf1db-83ad-47dd-a743-7f5c618d528e");
			public const string AuthorFieldName = "Author";
			
		
			
			public static readonly ID DateFieldId = new ID("221bce6a-7d28-4a27-b89f-0b450b8ff08e");
			public const string DateFieldName = "Date";
			
		
			
			public static readonly ID LikesFieldId = new ID("f50e22b6-1e20-4c2d-8863-aefdba844fd2");
			public const string LikesFieldName = "Likes";
			
		
			
			public static readonly ID Main_BodyFieldId = new ID("60ade6be-767c-48ad-a49f-b55b463ada13");
			public const string Main_BodyFieldName = "Main Body";
			
		
			
			public static readonly ID Page_TitleFieldId = new ID("cbabc9e0-9797-4161-ada9-4b28e871d4a8");
			public const string Page_TitleFieldName = "Page Title";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Article_Details
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Article Details</para>	
	/// <para>ID: 11a7b1bf-f409-4a99-9706-6b24224eae33</para>	
	/// </summary>
	[SitecoreType(TemplateId=IArticle_DetailsConstants.TemplateIdString)] //, Cachable = true
	public partial class Article_Details  : GlassBase, IArticle_Details 
	{
	   
		
				/// <summary>
				/// The Article Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: fe1e0961-6a48-44f0-be52-9af346a068ad</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.Article_ImageFieldName)]
				public virtual Image Article_Image  {get; set;}
					
		
				/// <summary>
				/// The Author field.
				/// <para></para>
				/// <para>Field Type: lookup</para>		
				/// <para>Field ID: f8bcf1db-83ad-47dd-a743-7f5c618d528e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.AuthorFieldName)]
				public virtual Guid Author  {get; set;}
					
		
				/// <summary>
				/// The Date field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 221bce6a-7d28-4a27-b89f-0b450b8ff08e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.DateFieldName)]
				public virtual DateTime Date  {get; set;}
					
		
				/// <summary>
				/// The Likes field.
				/// <para></para>
				/// <para>Field Type: Number</para>		
				/// <para>Field ID: f50e22b6-1e20-4c2d-8863-aefdba844fd2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.LikesFieldName)]
				public virtual float Likes  {get; set;}
					
		
				/// <summary>
				/// The Main Body field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 60ade6be-767c-48ad-a49f-b55b463ada13</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.Main_BodyFieldName)]
				public virtual string Main_Body  {get; set;}
					
		
				/// <summary>
				/// The Page Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: cbabc9e0-9797-4161-ada9-4b28e871d4a8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.Page_TitleFieldName)]
				public virtual string Page_Title  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticle_DetailsConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Pages
{


 	/// <summary>
	/// IAuthor Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Author</para>	
	/// <para>ID: 37cc391d-05e8-42b1-8ffa-97a1bedfd258</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthorConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAuthor : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Bio field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 8340b53e-5f2d-40c9-b6d3-ccd872e28cbc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthorConstants.BioFieldName)]
					string Bio  {get; set;}
			
			
					/// <summary>
					/// The Date of Birth field.
					/// <para></para>
					/// <para>Field Type: Date</para>		
					/// <para>Field ID: 1bd42e86-d736-421c-bad6-42944bb11193</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthorConstants.Date_Of_BirthFieldName)]
					DateTime Date_Of_Birth  {get; set;}
			
			
					/// <summary>
					/// The Full Name field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ac4a4ea4-42f9-4387-a113-1ec40b17c844</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthorConstants.Full_NameFieldName)]
					string Full_Name  {get; set;}
			
			
					/// <summary>
					/// The Profile Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: de28c9c4-43d1-4779-a0c0-adea117dbf90</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthorConstants.Profile_ImageFieldName)]
					Image Profile_Image  {get; set;}
			
			
	}


	public static partial class IAuthorConstants{

			public const string TemplateIdString = "37cc391d-05e8-42b1-8ffa-97a1bedfd258";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Author";

		
			
			public static readonly ID BioFieldId = new ID("8340b53e-5f2d-40c9-b6d3-ccd872e28cbc");
			public const string BioFieldName = "Bio";
			
		
			
			public static readonly ID Date_Of_BirthFieldId = new ID("1bd42e86-d736-421c-bad6-42944bb11193");
			public const string Date_Of_BirthFieldName = "Date of Birth";
			
		
			
			public static readonly ID Full_NameFieldId = new ID("ac4a4ea4-42f9-4387-a113-1ec40b17c844");
			public const string Full_NameFieldName = "Full Name";
			
		
			
			public static readonly ID Profile_ImageFieldId = new ID("de28c9c4-43d1-4779-a0c0-adea117dbf90");
			public const string Profile_ImageFieldName = "Profile Image";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Author
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Author</para>	
	/// <para>ID: 37cc391d-05e8-42b1-8ffa-97a1bedfd258</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthorConstants.TemplateIdString)] //, Cachable = true
	public partial class Author  : GlassBase, IAuthor 
	{
	   
		
				/// <summary>
				/// The Bio field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 8340b53e-5f2d-40c9-b6d3-ccd872e28cbc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.BioFieldName)]
				public virtual string Bio  {get; set;}
					
		
				/// <summary>
				/// The Date of Birth field.
				/// <para></para>
				/// <para>Field Type: Date</para>		
				/// <para>Field ID: 1bd42e86-d736-421c-bad6-42944bb11193</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.Date_Of_BirthFieldName)]
				public virtual DateTime Date_Of_Birth  {get; set;}
					
		
				/// <summary>
				/// The Full Name field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ac4a4ea4-42f9-4387-a113-1ec40b17c844</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.Full_NameFieldName)]
				public virtual string Full_Name  {get; set;}
					
		
				/// <summary>
				/// The Profile Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: de28c9c4-43d1-4779-a0c0-adea117dbf90</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.Profile_ImageFieldName)]
				public virtual Image Profile_Image  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Pages
{


 	/// <summary>
	/// IHome Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Home</para>	
	/// <para>ID: 56f3ef27-e3cf-4822-af0c-3a0f4b3b965c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHome : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Address field.
					/// <para></para>
					/// <para>Field Type: Address Field</para>		
					/// <para>Field ID: 14a57c2d-6f57-45a0-b1b2-3ca86cbbee36</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.AddressFieldName)]
					object /* UNKNOWN */ Address  {get; set;}
			
			
					/// <summary>
					/// The Html field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 31449dd2-7c4d-41a6-bedf-d332250f6416</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.HtmlFieldName)]
					string Html  {get; set;}
			
			
					/// <summary>
					/// The Page Header field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: fbdc1f55-5fb8-4198-9a8b-9364b57d4a23</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.Page_HeaderFieldName)]
					string Page_Header  {get; set;}
			
			
					/// <summary>
					/// The Slider Images field.
					/// <para></para>
					/// <para>Field Type: TreelistEx</para>		
					/// <para>Field ID: 92bc7e7a-0371-4f8d-98f0-edb58207d6a4</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.Slider_ImagesFieldName)]
					IEnumerable<Guid> Slider_Images  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 978c53ad-fcc4-4deb-9949-8b5838fdda0c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
					/// <summary>
					/// The Youtube Video field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 0162366e-b2c0-40c2-ab54-7021cd5ec790</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHomeConstants.Youtube_VideoFieldName)]
					string Youtube_Video  {get; set;}
			
			
	}


	public static partial class IHomeConstants{

			public const string TemplateIdString = "56f3ef27-e3cf-4822-af0c-3a0f4b3b965c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Home";

		
			
			public static readonly ID AddressFieldId = new ID("14a57c2d-6f57-45a0-b1b2-3ca86cbbee36");
			public const string AddressFieldName = "Address";
			
		
			
			public static readonly ID HtmlFieldId = new ID("31449dd2-7c4d-41a6-bedf-d332250f6416");
			public const string HtmlFieldName = "Html";
			
		
			
			public static readonly ID Page_HeaderFieldId = new ID("fbdc1f55-5fb8-4198-9a8b-9364b57d4a23");
			public const string Page_HeaderFieldName = "Page Header";
			
		
			
			public static readonly ID Slider_ImagesFieldId = new ID("92bc7e7a-0371-4f8d-98f0-edb58207d6a4");
			public const string Slider_ImagesFieldName = "Slider Images";
			
		
			
			public static readonly ID TitleFieldId = new ID("978c53ad-fcc4-4deb-9949-8b5838fdda0c");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID Youtube_VideoFieldId = new ID("0162366e-b2c0-40c2-ab54-7021cd5ec790");
			public const string Youtube_VideoFieldName = "Youtube Video";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Home
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Home</para>	
	/// <para>ID: 56f3ef27-e3cf-4822-af0c-3a0f4b3b965c</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomeConstants.TemplateIdString)] //, Cachable = true
	public partial class Home  : GlassBase, IHome 
	{
	   
		
				/// <summary>
				/// The Address field.
				/// <para></para>
				/// <para>Field Type: Address Field</para>		
				/// <para>Field ID: 14a57c2d-6f57-45a0-b1b2-3ca86cbbee36</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.AddressFieldName)]
				public virtual object /* UNKNOWN */ Address  {get; set;}
					
		
				/// <summary>
				/// The Html field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 31449dd2-7c4d-41a6-bedf-d332250f6416</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.HtmlFieldName)]
				public virtual string Html  {get; set;}
					
		
				/// <summary>
				/// The Page Header field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: fbdc1f55-5fb8-4198-9a8b-9364b57d4a23</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Page_HeaderFieldName)]
				public virtual string Page_Header  {get; set;}
					
		
				/// <summary>
				/// The Slider Images field.
				/// <para></para>
				/// <para>Field Type: TreelistEx</para>		
				/// <para>Field ID: 92bc7e7a-0371-4f8d-98f0-edb58207d6a4</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Slider_ImagesFieldName)]
				public virtual IEnumerable<Guid> Slider_Images  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 978c53ad-fcc4-4deb-9949-8b5838fdda0c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Youtube Video field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 0162366e-b2c0-40c2-ab54-7021cd5ec790</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Youtube_VideoFieldName)]
				public virtual string Youtube_Video  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomeConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Pages
{


 	/// <summary>
	/// IArticles Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Articles</para>	
	/// <para>ID: 5cfcbc7f-72f2-4d90-8640-b36d9fe79e5a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IArticlesConstants.TemplateIdString )] //, Cachable = true
	public partial interface IArticles : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Articles field.
					/// <para></para>
					/// <para>Field Type: tree list</para>		
					/// <para>Field ID: c7fa39f5-c45f-4356-8d82-564e1278ae70</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticlesConstants.ArticlesFieldName)]
					object /* UNKNOWN */ ArticlesList  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e3b05dc5-1a89-4dfd-85a0-70bf62eef4cb</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IArticlesConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IArticlesConstants{

			public const string TemplateIdString = "5cfcbc7f-72f2-4d90-8640-b36d9fe79e5a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Articles";

		
			
			public static readonly ID ArticlesFieldId = new ID("c7fa39f5-c45f-4356-8d82-564e1278ae70");
			public const string ArticlesFieldName = "Articles";
			
		
			
			public static readonly ID TitleFieldId = new ID("e3b05dc5-1a89-4dfd-85a0-70bf62eef4cb");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Articles
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Articles</para>	
	/// <para>ID: 5cfcbc7f-72f2-4d90-8640-b36d9fe79e5a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IArticlesConstants.TemplateIdString)] //, Cachable = true
	public partial class Articles  : GlassBase, IArticles 
	{
	   
		
				/// <summary>
				/// The Articles field.
				/// <para></para>
				/// <para>Field Type: tree list</para>		
				/// <para>Field ID: c7fa39f5-c45f-4356-8d82-564e1278ae70</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticlesConstants.ArticlesFieldName)]
				public virtual object /* UNKNOWN */ ArticlesList  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e3b05dc5-1a89-4dfd-85a0-70bf62eef4cb</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticlesConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticlesConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticlesConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticlesConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IArticlesConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Pages
{


 	/// <summary>
	/// IAuthors Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Authors</para>	
	/// <para>ID: 5e3e3e4e-1b2e-4d1b-aefb-2a513aaa310b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthorsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAuthors : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Authors field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: ff219e5f-79ab-43eb-b375-2daa2888bfa0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthorsConstants.AuthorsFieldName)]
					IEnumerable<Guid> AuthorsList  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 09cfecbb-d50e-4e58-b7ac-e78fca62e63d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAuthorsConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IAuthorsConstants{

			public const string TemplateIdString = "5e3e3e4e-1b2e-4d1b-aefb-2a513aaa310b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Authors";

		
			
			public static readonly ID AuthorsFieldId = new ID("ff219e5f-79ab-43eb-b375-2daa2888bfa0");
			public const string AuthorsFieldName = "Authors";
			
		
			
			public static readonly ID TitleFieldId = new ID("09cfecbb-d50e-4e58-b7ac-e78fca62e63d");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Authors
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Authors</para>	
	/// <para>ID: 5e3e3e4e-1b2e-4d1b-aefb-2a513aaa310b</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAuthorsConstants.TemplateIdString)] //, Cachable = true
	public partial class Authors  : GlassBase, IAuthors 
	{
	   
		
				/// <summary>
				/// The Authors field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: ff219e5f-79ab-43eb-b375-2daa2888bfa0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorsConstants.AuthorsFieldName)]
				public virtual IEnumerable<Guid> AuthorsList  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 09cfecbb-d50e-4e58-b7ac-e78fca62e63d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorsConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorsConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorsConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorsConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAuthorsConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Parameters
{


 	/// <summary>
	/// ITest_Parameter Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Parameters/Test Parameter</para>	
	/// <para>ID: 6a3fd3da-c914-43f0-be3d-b0a74a5d591f</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITest_ParameterConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITest_Parameter : IGlassBase 
	{
			
					/// <summary>
					/// The Value field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 53c47a96-b783-49bb-a391-371ca09ebc9d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ITest_ParameterConstants.ValueFieldName)]
					string Value  {get; set;}
			
			
	}


	public static partial class ITest_ParameterConstants{

			public const string TemplateIdString = "6a3fd3da-c914-43f0-be3d-b0a74a5d591f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Test Parameter";

		
			
			public static readonly ID ValueFieldId = new ID("53c47a96-b783-49bb-a391-371ca09ebc9d");
			public const string ValueFieldName = "Value";
			
			

	}

	
	/// <summary>
	/// Test_Parameter
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Parameters/Test Parameter</para>	
	/// <para>ID: 6a3fd3da-c914-43f0-be3d-b0a74a5d591f</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITest_ParameterConstants.TemplateIdString)] //, Cachable = true
	public partial class Test_Parameter  : GlassBase, ITest_Parameter 
	{
	   
		
				/// <summary>
				/// The Value field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 53c47a96-b783-49bb-a391-371ca09ebc9d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITest_ParameterConstants.ValueFieldName)]
				public virtual string Value  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Pages
{


 	/// <summary>
	/// IComment Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Comment</para>	
	/// <para>ID: 6b2711c9-67d8-43a2-aa0c-8afe9393d723</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IComment : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Comment Author field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 4554869c-5ff2-48b4-9a1c-7da711b25dcc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.Comment_AuthorFieldName)]
					string Comment_Author  {get; set;}
			
			
					/// <summary>
					/// The Comment Text field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: b346356c-0c17-4a87-8b11-e4460ae820e8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICommentConstants.Comment_TextFieldName)]
					string Comment_Text  {get; set;}
			
			
	}


	public static partial class ICommentConstants{

			public const string TemplateIdString = "6b2711c9-67d8-43a2-aa0c-8afe9393d723";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Comment";

		
			
			public static readonly ID Comment_AuthorFieldId = new ID("4554869c-5ff2-48b4-9a1c-7da711b25dcc");
			public const string Comment_AuthorFieldName = "Comment Author";
			
		
			
			public static readonly ID Comment_TextFieldId = new ID("b346356c-0c17-4a87-8b11-e4460ae820e8");
			public const string Comment_TextFieldName = "Comment Text";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Comment
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Pages/Comment</para>	
	/// <para>ID: 6b2711c9-67d8-43a2-aa0c-8afe9393d723</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICommentConstants.TemplateIdString)] //, Cachable = true
	public partial class Comment  : GlassBase, IComment 
	{
	   
		
				/// <summary>
				/// The Comment Author field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 4554869c-5ff2-48b4-9a1c-7da711b25dcc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.Comment_AuthorFieldName)]
				public virtual string Comment_Author  {get; set;}
					
		
				/// <summary>
				/// The Comment Text field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: b346356c-0c17-4a87-8b11-e4460ae820e8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.Comment_TextFieldName)]
				public virtual string Comment_Text  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICommentConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Folders
{


 	/// <summary>
	/// IGlobal_Cinfiguration Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Folders/Global Cinfiguration</para>	
	/// <para>ID: ab0a5784-e080-40db-b365-36d7eb2f5bb0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGlobal_CinfigurationConstants.TemplateIdString )] //, Cachable = true
	public partial interface IGlobal_Cinfiguration : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase
	{
			
	}


	public static partial class IGlobal_CinfigurationConstants{

			public const string TemplateIdString = "ab0a5784-e080-40db-b365-36d7eb2f5bb0";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Global Cinfiguration";

			

	}

	
	/// <summary>
	/// Global_Cinfiguration
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Folders/Global Cinfiguration</para>	
	/// <para>ID: ab0a5784-e080-40db-b365-36d7eb2f5bb0</para>	
	/// </summary>
	[SitecoreType(TemplateId=IGlobal_CinfigurationConstants.TemplateIdString)] //, Cachable = true
	public partial class Global_Cinfiguration  : GlassBase, IGlobal_Cinfiguration 
	{
	   
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Account
{


 	/// <summary>
	/// IAccount_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Account/Account Page</para>	
	/// <para>ID: ab51e15c-c529-45c7-8d20-8e8d9bfe6272</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAccount_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAccount_Page : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase_Page
	{
			
					/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: c21e4db9-8646-43fb-8009-0ed95abc722f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAccount_PageConstants.BodyFieldName)]
					string Body  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 985d5abb-c80c-4155-8097-83bcb1b83e42</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAccount_PageConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IAccount_PageConstants{

			public const string TemplateIdString = "ab51e15c-c529-45c7-8d20-8e8d9bfe6272";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Account Page";

		
			
			public static readonly ID BodyFieldId = new ID("c21e4db9-8646-43fb-8009-0ed95abc722f");
			public const string BodyFieldName = "Body";
			
		
			
			public static readonly ID TitleFieldId = new ID("985d5abb-c80c-4155-8097-83bcb1b83e42");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Account_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Account/Account Page</para>	
	/// <para>ID: ab51e15c-c529-45c7-8d20-8e8d9bfe6272</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAccount_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Account_Page  : GlassBase, IAccount_Page 
	{
	   
		
				/// <summary>
				/// The Body field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: c21e4db9-8646-43fb-8009-0ed95abc722f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAccount_PageConstants.BodyFieldName)]
				public virtual string Body  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 985d5abb-c80c-4155-8097-83bcb1b83e42</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAccount_PageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAccount_PageConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAccount_PageConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAccount_PageConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAccount_PageConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Folders
{


 	/// <summary>
	/// ISite_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Folders/Site Folder</para>	
	/// <para>ID: eddca74f-d819-48d1-928e-b2441c41e367</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite_Folder : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase
	{
			
	}


	public static partial class ISite_FolderConstants{

			public const string TemplateIdString = "eddca74f-d819-48d1-928e-b2441c41e367";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site Folder";

			

	}

	
	/// <summary>
	/// Site_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Folders/Site Folder</para>	
	/// <para>ID: eddca74f-d819-48d1-928e-b2441c41e367</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Site_Folder  : GlassBase, ISite_Folder 
	{
	   
			
	}

}
namespace SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base
{


 	/// <summary>
	/// IBase_Page Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Base/Base Page</para>	
	/// <para>ID: f2651ec9-b4c0-4c55-8bf4-890ed4cfac33</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_PageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBase_Page : IGlassBase , global::SiteCoreTrainings.TDS_Entities.TDS_Gen.Trainings.Base.IBase
	{
			
					/// <summary>
					/// The FooterContent field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_PageConstants.FooterContentFieldName)]
					string FooterContent  {get; set;}
			
			
					/// <summary>
					/// The Meta Description field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_PageConstants.Meta_DescriptionFieldName)]
					string Meta_Description  {get; set;}
			
			
					/// <summary>
					/// The Meta Keywords field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_PageConstants.Meta_KeywordsFieldName)]
					string Meta_Keywords  {get; set;}
			
			
					/// <summary>
					/// The Meta Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBase_PageConstants.Meta_TitleFieldName)]
					string Meta_Title  {get; set;}
			
			
	}


	public static partial class IBase_PageConstants{

			public const string TemplateIdString = "f2651ec9-b4c0-4c55-8bf4-890ed4cfac33";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Base Page";

		
			
			public static readonly ID FooterContentFieldId = new ID("98b43507-8c2c-443c-bf65-1a72a1357fc2");
			public const string FooterContentFieldName = "FooterContent";
			
		
			
			public static readonly ID Meta_DescriptionFieldId = new ID("852b5364-8f11-4a55-9dbc-7f3d4022a179");
			public const string Meta_DescriptionFieldName = "Meta Description";
			
		
			
			public static readonly ID Meta_KeywordsFieldId = new ID("38b84772-078f-4e4c-9715-a5fe9254aeb3");
			public const string Meta_KeywordsFieldName = "Meta Keywords";
			
		
			
			public static readonly ID Meta_TitleFieldId = new ID("754c4413-bc38-4902-a1d6-8ef0046e250a");
			public const string Meta_TitleFieldName = "Meta Title";
			
			

	}

	
	/// <summary>
	/// Base_Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/Trainings/Base/Base Page</para>	
	/// <para>ID: f2651ec9-b4c0-4c55-8bf4-890ed4cfac33</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBase_PageConstants.TemplateIdString)] //, Cachable = true
	public partial class Base_Page  : GlassBase, IBase_Page 
	{
	   
		
				/// <summary>
				/// The FooterContent field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 98b43507-8c2c-443c-bf65-1a72a1357fc2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_PageConstants.FooterContentFieldName)]
				public virtual string FooterContent  {get; set;}
					
		
				/// <summary>
				/// The Meta Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 852b5364-8f11-4a55-9dbc-7f3d4022a179</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_PageConstants.Meta_DescriptionFieldName)]
				public virtual string Meta_Description  {get; set;}
					
		
				/// <summary>
				/// The Meta Keywords field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 38b84772-078f-4e4c-9715-a5fe9254aeb3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_PageConstants.Meta_KeywordsFieldName)]
				public virtual string Meta_Keywords  {get; set;}
					
		
				/// <summary>
				/// The Meta Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 754c4413-bc38-4902-a1d6-8ef0046e250a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBase_PageConstants.Meta_TitleFieldName)]
				public virtual string Meta_Title  {get; set;}
					
			
	}

}
